### ISSUE TITLE
TypeError: JSON.parse(...).map is not a function

### ISSUE THREAD

**Issue by qburst-hari** [wswebcreation/wdio-multiple-cucumber-html-reporter#21]
**Environment (please complete the following information):**
 - Node.js version: 8.9.4
 - NPM version: 6.4.1
 - webdriver.io version: 4.13.2
 - wdio-cucumber-framework version: 2.2.7
 - wdio-multiple-cucumber-html-reporter version: 0.3.3
**Config of webdriver.io and the reporter**

```
  reporters: ['spec', 'html-format', 'dot', 'multiple-cucumber-html'],
  reporterOptions: {
    outputDir: 'outputDir',
    htmlFormat: {
      outputDir: './reports/html-reports/'
    },
    htmlReporter: {
      jsonFolder: './',
      reportFolder: './',
      // ... other options, see Options
    },
  },
```
**Describe the bug**
Once I execute, json file is created but after that its showing error as `TypeError: JSON.parse(...).map is not a function`

**Comment by wswebcreation** [comment]
Hi @qburst-hari 

Can you share the the JSON-file and some more logging?

**Comment by qburst-hari** [comment]
Its fixed, I used the json default report from webdriverio and issue resolved

**Comment by SebastianStavar** [comment]
The reason this happens is because at line 23 in collect-jsons.js the lib does            `JSON.parse(data).map((json) ... `. 
Now _data_ represents the content of the json files (one by one) found in the folder specified in config (**jsonFolder:**). 
But the way those files are gathered is by using fileSync (`files = find.fileSync(/\.json$/, path.resolve(process.cwd(), options.jsonDir));`) which will get all json files in that folder **and its subfolders.** 
Because you put the report (**reportFolder:**) in the same place as the json logs your next run will also try to parse the jsons part of the report generation (eg enriched-output.json) which is not an array so you can't run map on it, hence the error.
You need to either change the report folder or set **removeFolders: true** in the config file.

**Comment by TriTrieu** [comment]
> The reason this happens is because at line 23 in collect-jsons.js the lib does `JSON.parse(data).map((json) ... `.
> Now _data_ represents the content of the json files (one by one) found in the folder specified in config (**jsonFolder:**).
> But the way those files are gathered is by using fileSync (`files = find.fileSync(/\.json$/, path.resolve(process.cwd(), options.jsonDir));`) which will get all json files in that folder **and its subfolders.**
> Because you put the report (**reportFolder:**) in the same place as the json logs your next run will also try to parse the jsons part of the report generation (eg enriched-output.json) which is not an array so you can't run map on it, hence the error.
> You need to either change the report folder or set **removeFolders: true** in the config file.

The solution is working for me
