### ISSUE TITLE
Running cucumber tests, with the `jsonFolder` path existing, causes error

### ISSUE THREAD

**Issue by FlippieCoetser** [wswebcreation/wdio-multiple-cucumber-html-reporter#4]
**Actual:**
Background:
Given the `jsonFolder` path configured does not exist,
When I run all Cucumber Tests,
And a HTML Report is produced 

Scenario:
When I run all Cucumber Test for a second time,
And the `jsonFolder` path configured does exist
Then a `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string` is produced

**Expected:**
Background:
Given the `jsonFolder` path configured does not exist,
When I run all Cucumber Tests,
And a HTML Report is produced 

Scenario:
When I run all Cucumber Test for a second time,
And the `jsonFolder` path configured does exist
Then a new HTML Report should be produced

Workaround:
Ensure the `jsonFolder` path configured does not exist prior to running the Cucumber tests.

**Comment by wswebcreation** [comment]
🤔 ,

On what platform are you (Windows / OSX) and which node + npm version? I can't seem tp reproduce this

**Comment by FlippieCoetser** [comment]
@wswebcreation Windows 10 and Node version v9.4.0.

**Comment by FlippieCoetser** [comment]
@wswebcreation could help and try to fix but I run into more errors when I do:
1) Git Clone
2) npm install
3) npm run complie
4) npm run test

The last step fails with `TypeError: Cannot read property 'browserName` of undefined.

**Comment by FlippieCoetser** [comment]
Chrome

**Comment by wswebcreation** [comment]
Hmm,

I see the second problem. This has to do with the fact that I didn't use the selenium standalone  but a global on my machine. I've added it to the devdependencies and to the config. 
For testing you should have FireFox and Chrome installed on your machine (will update the docs for it).

I now also see the initial problem. Will dive into it, hope to have a fix tomorrow (I didn't see it because I always clean my folder in a preprocess, see my testconfig)

**Comment by FlippieCoetser** [comment]
version `0.1.2` resolves the problem. Thanks!

**Comment by wswebcreation** [comment]
Thank you for seeing this
