### ISSUE TITLE
wdio multiple cucumber report not showing the parameter passed using Scenario Outline Example

### ISSUE THREAD

**Issue by shabfactor** [wswebcreation/wdio-multiple-cucumber-html-reporter#7]
**Environment (please complete the following information):**
 - Node.js version: 8.11.3
 - NPM version: 5.6.0
 - webdriver.io version: 4.10.1
 - wdio-cucumber-framework version:1.3.2
 - wdio-multiple-cucumber-html-reporter version: 0.1.3

**Config of webdriver.io and the reporter**
An example of how you configured the reporter in your webdriver.io config
 

> reporterOptions: {
>         htmlReporter: {
>             jsonFolder: './tmp',
>             reportFolder: './tmp/report',
>             displayDuration: true,
>             durationInMS: true,
>             jsonDir: true,
>             saveCollectedJSON: true,
>         }
>     },

**Describe the bug**
The parameters passed in Scenario Outline e.g.

> Scenario Outline: I want to validate my vehicle detail field names
>         Given I enter my registration number "<rego>"
>         Then  I receive my vehicle details field names
>         Examples:
>             | rego   |
>            | TEST03 |

is not showing in the report e.g. in screenshot
![report_screenshot](https://user-images.githubusercontent.com/6949709/44007603-d73952cc-9eec-11e8-89c5-e686ac302402.PNG)

[Include code or an example repository that can easily be set up]
none
**Expected behavior**
i suppose to see the parameter "TEST03" in the report in the empty "" place.

**Snapshots**
attached

**Additional context**

**Comment by wswebcreation** [comment]
Hi @shabfactor

Tnx for filling the issue. I'm currently not available to check it due to vacation. 

Keep you posted

**Comment by filfreire** [comment]
@shabfactor @wswebcreation a quick workaround for me that fixed this issue:

set  ` "wdio-cucumber-framework": "^1.1.0",`  instead of version `2.2.2`

This issue might be related with `wdio-cucumber-framework`. I've noticed that for other reporters version `2.2.2` doesn't seem to be working properly for scenario outlines, and omits example values in execution reports of scenario outlines.

For example, for `spec` reporter, if I use version `1.1.0`, the Example values appear in each execution, and the scenario is properly indented, both on `spec` as well as in `wdio-multiple-cucumber-html-reporter`.

![spec_formatter](https://user-images.githubusercontent.com/11976836/44032141-96b7c7f0-9f06-11e8-8abf-33344252ba07.png)

For `2.2.2` on the other hand, the example values don't appear, and in the case of `spec` reporter, the scenarios execution indents endlessly:
![spec_formatter_wdio-cuc-222](https://user-images.githubusercontent.com/11976836/44032140-96939c54-9f06-11e8-8616-f44fdb3db027.png)

Related issue https://github.com/webdriverio/wdio-cucumber-framework/issues/111

Related comments:
https://github.com/webdriverio/wdio-cucumber-framework/issues/111#issuecomment-406558851
https://github.com/webdriverio/wdio-cucumber-framework/issues/111#issuecomment-406557640

/cc @christian-bromann

**Comment by shabfactor** [comment]
@filfreire @wswebcreation /cc @christian-bromann

Thanks @filfreire  going back to  "wdio-cucumber-framework": "^1.1.0"  fixed the issue. Really appreciate if someone can have a look at "wdio-cucumber-framework": "^2.2.2" version?

**Comment by wswebcreation** [comment]
Hi @shabfactor 

This is an issue in `wdio-cucumber-framework`. The scenario name and the step name are not processed so they get the correct value from the `Examples` key.

I've created a new release so it will now show the key in the output. The reason why it didn't show the key and showed what you have what that the browser saw it as an HTML tag. With version `0.2.0` it will now show it as this

![image](https://user-images.githubusercontent.com/11979740/44306783-ee674500-a395-11e8-9f4e-c4e6fd231e5c.png)

when this is the featurefile

```bash
Feature: Create scenario outline feature
    This is a feature description
    Second description

    Scenario Outline: a scenario outline key:<key>
        Given an outline <key> step
        When I'm a scenario when step
        Then I'm a scenario then step

        Examples:
            | key       |
            | outline 1 |
            | outline 2 |
```

When I have time I'm going to file an issue for this with the explanation of it

@shabfactor and @filfreire 
The spec reporter is broken because of `wdio-cucumber-framework`, see also issue https://github.com/webdriverio/wdio-cucumber-framework/issues/129

You don't need to revert to version `1.1.0` if you don't mind the indentation and the scenario outline keys not being shown. This report will still work. If you revert to `1.1.0` the report will also work but you miss a lot of essential data, see the [FAQ](https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter#i-dont-see-the-keywords-given-when-then-in-the-report)

I'm going to close this issue now because it's an external bug, but it's still open for discussion
